### ISSUE TITLE
Contribute to this Jekyll theme for Hacktoberfest 2017

### ISSUE THREAD

**Issue by scottmathson** [scottmathson/simpol-theme#1]
Hello! [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/) is here!

## Rules

>To get a shirt, you must make four pull requests between October 1–31 in any timezone. Pull requests can be to any public repo on GitHub, not just the ones we’ve highlighted. The pull request must contain commits you made yourself. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.

I'm seeking any kind of contributions to Simpol Theme, including:

- Fixing typos
- Improving documentation
- Misc. optimizations
- Feeling generous? New features!?

Be sure to add the Hacktoberfest label to any PRs.

**Comment by scottmathson** [comment]
Hmmm maybe I should start by checking out resources for the best `contributing.md` and code of conduct files. 

Any recommendations anyone?

**Comment by omegahm** [comment]
The `CONTRIBUTING.md` file doesn't have to be huge and thorough; it can be small and to the point. Take a look at the one in Rails: https://github.com/rails/rails/blob/master/CONTRIBUTING.md. I might make a PR for you with it. :smile:

**Comment by scottmathson** [comment]
Thanks, that would be awesome! ;-) I'll get to it once off the road, done traveling, otherwise. Cheers @omegahm

**Comment by mkasberg** [comment]
I opened a pull request to fix a warning from your `_config.yml`. See #4 and let me know what you think.

**Comment by lisaychuang** [comment]
I read through Contributing.md, Readme.md, and _posts/2017-04-16-writing-new-post.markdown . No typo spotted so far!

**Comment by scottmathson** [comment]
Thanks for the contributions thus far, has been fun merging these additions into master! Cheers

**Comment by scottmathson** [comment]
Published a new release and pushed updated gem to Ruby Gems. Thanks for contributions, all!

https://rubygems.org/gems/simpol-jekyll-theme/versions/1.0.5
https://github.com/scottmathson/simpol-theme/releases/tag/1.0.5

**Comment by scottmathson** [comment]
Thanks again everyone 🤘
